### PR TITLE
Minor UI update

### LINKED ISSUE #216: Button broken in destination detail page
## Screenshots
IMG_20210303_005013

### PR DESCRIPTION
**Pull request by lespaceman**
Subject: "Button broken in destination detail page #216 "
Assignees: "Kites-hackathon-squad"

# Fixes #216

The map button looked broken in smaller devices, after consulting with the design team, I changed the text inside the button and adjusted the margins.

Screenshot 2021-09-13 at 6 24 49 PM Screenshot 2021-09-13 at 6 24 30 PM

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

Screenshot 2021-09-13 at 6 24 49 PM Screenshot 2021-09-13 at 6 24 30 PM
</details>

### CODE REVIEW

**Comment by akhilmhdh** [comment]
@lespaceman Kindly fill the details on the PR template to get better context. Also please follow https://www.conventionalcommits.org/en/v1.0.0/ for commits. 

CC: @gautamkrishnar

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
@akhilmhdh conventional commit changes can be ignored for now since this repo didn't have that as a guideline.

@lespaceman please update the PR's description according to the PR template, also please attach a screenshot. It will help us to keep track of the changes in the future,

**Comment by lespaceman** [comment]
> @akhilmhdh conventional commit changes can be ignored for now since this repo didn't have that as a guideline.
> 
> @lespaceman please update the PR's description according to the PR template, also please attach a screenshot. It will help us to keep track of the changes in the future.

@gautamkrishnar @akhilmhdh updated the description according to the PR template.

**Review by gautamkrishnar — APPROVED** [review]
👍🏻  LGTM

**Pull request merged**
