### PR TITLE
Add second splash screen

### PR DESCRIPTION
**Pull request by nikhilnathr**
- A second splash screen is shown on first app load for 2000ms.

## Screenshots

<details>
<summary>View Screenshots</summary>

image

</details>

### CODE REVIEW

**Comment by akhilmhdh** [comment]
@nikhilnathr Hey man.
Just a suggestion. Why not use CSS for adding splash effect. Using JS like that causes unnecessary rendering and memory where CSS can do it easily. It will also make the code quality better too. 😄

**Comment by akhilmhdh** [comment]
@nikhilnathr First of all its a bad thing to do rendering without giving dependencies. If the dom renders again. This would also re-render. 

Next never give timeout without clear mechanism. It must be cleared or it causes memory leak. 

The issue with this splash screen is its abrupt change rather a smoother one would be preferable.

**Comment by nikhilnathr** [comment]
@akhilmhdh The SplashScreen component is inside the App component. So I think, this would only get re-rendered the App gets re-rendered. Re-rendering the App component is anyways a costly operation so would not be done ideally.

For clearing the timeout, I didn't include it because the SplashScreen screen `useEffect` has the dependancy `duration`. `duration` would ideally be not changed for the SplashScreen. So, the `useEffect` will only be run once, if the `duration` is not mutated by a state. But even though it is correct for this particular component, it may result in memory leaks if used in that way. So, I will clear the timeout during the cleanup of `useEffect`. Thank you for pointing that out.

I didn't get what you meant by the abrupt change. Can you elaborate / suggest a solution?

**Comment by lespaceman** [comment]
Looks like this is good to go.

**Review by lespaceman — APPROVED** [review]

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
Implementing a seporate splash screen on rendering react is a bad idea. Splash is something that should show up on DOMContentLoaded. The app already have a splash screen that is provided by chrome via parsing the manifest file. 

App shouldn't have two splash screens:
https://siasky.net/AAC05Cn3HgfZp9inqW6QuRSbyZguug7EF8Plb7ZeEi-1_Q

**Comment by lespaceman** [comment]
@gautamkrishnar We have a requirement to display the government logo during the start of the app.  Splashscreen doesn't allow us to use multiple logos. I guess we may remove the original splash screen and use this instead. But do you think we can go ahead with this implementation and change it later?

**Comment by gautamkrishnar** [comment]
Also UI is broken in IOS https://siasky.net/AADKFmbgvjKdB7lTLFZG4wGUkX_Q1pcCw8GjOasueyAjUA

**Comment by gautamkrishnar** [comment]
> @gautamkrishnar We have a requirement to display the government logo during the start of the app. Splashscreen doesn't allow us to use multiple logos. I guess we may remove the original splash screen and use this instead. But do you think we can go ahead with this implementation and change it later?

If we have that urgent requirement then it would be ok for now. But we should fix the IOS issue before it can be merged.

**Review by lespaceman — APPROVED** [review]

**Comment by gautamkrishnar** [comment]
@lespaceman please dont merge the pull request that is assigned to someone else. It should be merged by the person who is assigned. Its a common principle that we follow in the community.

**Pull request merged**
