### PR TITLE
carousel spacing issue

### LINKED ISSUE #177: Add enough margin/padding to the last item in the carousels
## Describe the bug
Last item in the following carousel and all other carousels should have a right margin/padding as required:
Screenshot 2021-02-23 at 12 34 45 AM

It should be same as the following first item's left margin/padding:
Screenshot 2021-02-23 at 12 40 42 AM

### PR DESCRIPTION
**Pull request by daliyajohn**
closes #177

### CODE REVIEW

**Review by athul — APPROVED** [review]
LGTM

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
Hi @daliyajohn this was not the intended behaviour I described:

- There shouldn't be a gap on the left and right like this:


- The cards should overflow to the left and right similar to the current implementation:


- Only the last card should have the following spacing:

**Comment by gautamkrishnar** [comment]
Please note that @akhilmhdh is also working on fixing this in #207

**Comment by gautamkrishnar** [comment]
Hi @daliyajohn this issue has been fixed by #208, looks like it is a better way to implement the feature. Closing this PR since this is stale.

**Pull request closed without merging**
