### PR TITLE
Nearme page

### LINKED ISSUE #97: Near me page
## Is your feature request related to a problem? Please describe
No

## Describe the solution you'd like
final nearme page

### PR DESCRIPTION
**Pull request by RithikaSujith**
# Closes/Fixes/Resolves

### 
Fixes #97 
# Explain the feature/fix

## Does this PR introduce a breaking change

 
No

## Screenshots
nearme-1
nearme-2
nearme-3
nearme-4

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Comment by athul** [comment]
@Kites-Foundation/kites-hackathon-squad 

Why are there so many hardcoded values?

Is this a bug or something. I'm confused. Please correct me if I'm wrong in that case.@naseemshah

**Comment by athul** [comment]
The Build is failing too😅😅 Checking those logs

**Review by athul — COMMENTED** [review]
@riginoommen could you please look on why there are blank spaces on the deploy preview

**Comment by riginoommen** [comment]
Yes @athul got it.

**Comment by riginoommen** [comment]
@RithikaSujith can you please share the design which you are working I just want to check ✔ that is the in sync with the original one

**Comment by RithikaSujith** [comment]
> @RithikaSujith can you please share the design which you are working I just want to check ✔ that is the in sync with the original one

WhatsApp Image 2021-02-13 at 18 58 37 (1)
WhatsApp Image 2021-02-13 at 18 58 37

**Comment by athul** [comment]
@naseemshah Hey, the `RatingStars` component doesn't seem to render correctly. Is there anything that was missed

Ref: https://github.com/RithikaSujith/hello-munnar-frontend/blob/196978ed0affacd5a74a8bed5217cc6c4890067a/src/components/NearMe/thingstodo.js#L13

**Review by lespaceman — APPROVED** [review]

**Pull request merged**
