### PR TITLE
feat: Added Google Analytics

### PR DESCRIPTION
**Pull request by gautamkrishnar**
# Closes/Fixes/Resolves
n/a

### 

# Explain the feature/fix
- Added Google Analytics
- Added env file
- Updated lockfile to use v2
- Removed old mattomo tracking code

## Does this PR introduce a breaking change
No

## Screenshots
Screenshot 2021-02-19 at 3 07 47 AM

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@tomahawk-pilot can you please provide the temp GA ID you mentioned

**Comment by tomahawk-pilot** [comment]
> 
> 
> @tomahawk-pilot can you please provide the temp GA ID you mentioned

check your mail for an invite to analytics profile

**Comment by tomahawk-pilot** [comment]
can you remove the <Script> from index.html file which has mamoto analytics

**Comment by tomahawk-pilot** [comment]
@gautamkrishnar switch to js please

**Comment by gautamkrishnar** [comment]
@tomahawk-pilot Done the changes

**Review by tomahawk-pilot — APPROVED** [review]

**Pull request merged**
